# Generated by Django 6.1.1 on 2026-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('status', models.CharField(default='Request Received', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
