# Generated by Django 6.1.1 on 2026-09-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_agent_name',
            field=models.CharField(default='Rahul Kumar', max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_agent_phone',
            field=models.CharField(default='9876501234', max_length=15),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delivery_status',
            field=models.CharField(default='Not Delivered', max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='pickup_status',
            field=models.CharField(default='Pickup Pending', max_length=30),
        ),
    ]
